### ISSUE TITLE
Braking resistor

### ISSUE THREAD

**Issue by ba114** [o-devices/bldc-ffb-wheel#8]
What value braking resistor should be used? 19.5v 12.3A power supply.
The schema shows a picture of a 50W 12R. I read on your forum that you use a 50W 10R and have read about others using 50W 2R and 50W 5R.

**Comment by olukelo** [comment]
It will work with any of them. The idea is to choose resistor and then adjust `Braking resistor limit` on hardware tab. I sucesfully used 2R and 10R resistors. First you connect resistor and start with 1% of `Braking resistor limit`. Then start increasing it by 1 tick and experiment - you need to stop at the point when PSU stops to go into overvoltage protection mode. For example for my PSU (15v 13A) it works with value 5% for 2R resistor and 10% for 10R resistor. I will update README file with this information as well

**Comment by ba114** [comment]
does it create a braking effect at all times?

**Comment by ba114** [comment]
Resolved with latest update to readme
